# written by igvfagent sce2g benchmark -- drop into CRISPR_comparison/config/config.yml
comparisons:
  k562_sce2g_reference_geneuniverse:
    pred:
      scE2G: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Data/Interpreted/Downloads/20260922_150656_sce2g_k562/IGVFFI1706PNVV.tsv.gz"
      scE2G_ignoreTPM: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Data/Interpreted/Downloads/20260922_150656_sce2g_k562/IGVFFI1706PNVV.tsv.gz"
      ABC: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Data/Interpreted/Downloads/20260922_150656_sce2g_k562/IGVFFI1706PNVV.tsv.gz"
      ARC_E2G: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Data/Interpreted/Downloads/20260922_150656_sce2g_k562/IGVFFI1706PNVV.tsv.gz"
    expt:
      crispr: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Data/scE2G/resources/EPCrisprBenchmark_ensemble_data_GRCh38.intGENCODEv43.tsv.gz"
    pred_config: "/Users/hzhou/Research/Projects/Compute/IGVFagent/Docs/scE2G/20260922_185109_k562_sce2g_reference_geneuniverse/pred_config.txt"
